// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: order.proto

package order_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoOrderRequest) Reset() {
	*x = DoOrderRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoOrderRequest) ProtoMessage() {}

func (x *DoOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoOrderRequest.ProtoReflect.Descriptor instead.
func (*DoOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *DoOrderRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *DoOrderRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *DoOrderRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *DoOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DoOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       int64                  `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	BaseResponse  *BaseResponse          `protobuf:"bytes,4,opt,name=BaseResponse,proto3" json:"BaseResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoOrderResponse) Reset() {
	*x = DoOrderResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoOrderResponse) ProtoMessage() {}

func (x *DoOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoOrderResponse.ProtoReflect.Descriptor instead.
func (*DoOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *DoOrderResponse) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *DoOrderResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DoOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DoOrderResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

type BaseResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RPCStatus           int64                  `protobuf:"varint,1,opt,name=RPCStatus,proto3" json:"RPCStatus,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	DisplayErrorMessage string                 `protobuf:"bytes,3,opt,name=DisplayErrorMessage,proto3" json:"DisplayErrorMessage,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResponse) GetRPCStatus() int64 {
	if x != nil {
		return x.RPCStatus
	}
	return 0
}

func (x *BaseResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BaseResponse) GetDisplayErrorMessage() string {
	if x != nil {
		return x.DisplayErrorMessage
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"\x84\x01\n" +
	"\x0eDoOrderRequest\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12 \n" +
	"\vProductName\x18\x02 \x01(\tR\vProductName\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\x03R\x06UserID\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\x03R\bQuantity\"\x96\x01\n" +
	"\x0fDoOrderResponse\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\x03R\aOrderID\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\x03R\x06Status\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x127\n" +
	"\fBaseResponse\x18\x04 \x01(\v2\x13.order.BaseResponseR\fBaseResponse\"\x82\x01\n" +
	"\fBaseResponse\x12\x1c\n" +
	"\tRPCStatus\x18\x01 \x01(\x03R\tRPCStatus\x12\"\n" +
	"\fErrorMessage\x18\x02 \x01(\tR\fErrorMessage\x120\n" +
	"\x13DisplayErrorMessage\x18\x03 \x01(\tR\x13DisplayErrorMessage2C\n" +
	"\x05Order\x12:\n" +
	"\aDoOrder\x12\x15.order.DoOrderRequest\x1a\x16.order.DoOrderResponse\"\x00B\rZ\vorder.protob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_proto_goTypes = []any{
	(*DoOrderRequest)(nil),  // 0: order.DoOrderRequest
	(*DoOrderResponse)(nil), // 1: order.DoOrderResponse
	(*BaseResponse)(nil),    // 2: order.BaseResponse
}
var file_order_proto_depIdxs = []int32{
	2, // 0: order.DoOrderResponse.BaseResponse:type_name -> order.BaseResponse
	0, // 1: order.Order.DoOrder:input_type -> order.DoOrderRequest
	1, // 2: order.Order.DoOrder:output_type -> order.DoOrderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
