// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: inventory.proto

package inventory_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductMasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductMasterRequest) Reset() {
	*x = ProductMasterRequest{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMasterRequest) ProtoMessage() {}

func (x *ProductMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMasterRequest.ProtoReflect.Descriptor instead.
func (*ProductMasterRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ProductMasterRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *ProductMasterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductMasterRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductMasterRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductMasterRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductMasterRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=Stock,proto3" json:"Stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockRequest) Reset() {
	*x = UpdateProductStockRequest{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockRequest) ProtoMessage() {}

func (x *UpdateProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductStockRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *UpdateProductStockRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=Message,proto3" json:"Message,omitempty"`
	Price         int64                  `protobuf:"varint,7,opt,name=Price,proto3" json:"Price,omitempty"`
	BaseResponse  *BaseResponse          `protobuf:"bytes,8,opt,name=BaseResponse,proto3" json:"BaseResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ProductResponse) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProductResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

type CheckProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductStockRequest) Reset() {
	*x = CheckProductStockRequest{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductStockRequest) ProtoMessage() {}

func (x *CheckProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductStockRequest.ProtoReflect.Descriptor instead.
func (*CheckProductStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *CheckProductStockRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

type CheckProductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=Stock,proto3" json:"Stock,omitempty"`
	BaseResponse  *BaseResponse          `protobuf:"bytes,3,opt,name=BaseResponse,proto3" json:"BaseResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductStockResponse) Reset() {
	*x = CheckProductStockResponse{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductStockResponse) ProtoMessage() {}

func (x *CheckProductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductStockResponse.ProtoReflect.Descriptor instead.
func (*CheckProductStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *CheckProductStockResponse) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *CheckProductStockResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CheckProductStockResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

type ReserveProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	OrderID       int64                  `protobuf:"varint,4,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductRequest) Reset() {
	*x = ReserveProductRequest{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductRequest) ProtoMessage() {}

func (x *ReserveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductRequest.ProtoReflect.Descriptor instead.
func (*ReserveProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveProductRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *ReserveProductRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReserveProductRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReserveProductRequest) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type ReserveProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ReserveStatus int64                  `protobuf:"varint,3,opt,name=ReserveStatus,proto3" json:"ReserveStatus,omitempty"`
	ReserveCount  int64                  `protobuf:"varint,4,opt,name=ReserveCount,proto3" json:"ReserveCount,omitempty"`
	BaseResponse  *BaseResponse          `protobuf:"bytes,6,opt,name=BaseResponse,proto3" json:"BaseResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductResponse) Reset() {
	*x = ReserveProductResponse{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductResponse) ProtoMessage() {}

func (x *ReserveProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductResponse.ProtoReflect.Descriptor instead.
func (*ReserveProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveProductResponse) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *ReserveProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveProductResponse) GetReserveStatus() int64 {
	if x != nil {
		return x.ReserveStatus
	}
	return 0
}

func (x *ReserveProductResponse) GetReserveCount() int64 {
	if x != nil {
		return x.ReserveCount
	}
	return 0
}

func (x *ReserveProductResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

type ReleaseProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProductRequest) Reset() {
	*x = ReleaseProductRequest{}
	mi := &file_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProductRequest) ProtoMessage() {}

func (x *ReleaseProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProductRequest.ProtoReflect.Descriptor instead.
func (*ReleaseProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseProductRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *ReleaseProductRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ReleaseProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	BaseResponse  *BaseResponse          `protobuf:"bytes,3,opt,name=BaseResponse,proto3" json:"BaseResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProductResponse) Reset() {
	*x = ReleaseProductResponse{}
	mi := &file_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProductResponse) ProtoMessage() {}

func (x *ReleaseProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProductResponse.ProtoReflect.Descriptor instead.
func (*ReleaseProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseProductResponse) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *ReleaseProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReleaseProductResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

type BaseResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RPCStatus           int64                  `protobuf:"varint,1,opt,name=RPCStatus,proto3" json:"RPCStatus,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,3,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	DisplayErrorMessage string                 `protobuf:"bytes,4,opt,name=DisplayErrorMessage,proto3" json:"DisplayErrorMessage,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *BaseResponse) GetRPCStatus() int64 {
	if x != nil {
		return x.RPCStatus
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BaseResponse) GetDisplayErrorMessage() string {
	if x != nil {
		return x.DisplayErrorMessage
	}
	return ""
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"\xa8\x01\n" +
	"\x14ProductMasterRequest\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bCategory\x18\x03 \x01(\tR\bCategory\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\x03R\x05Stock\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\x12\x14\n" +
	"\x05Price\x18\x06 \x01(\x03R\x05Price\"O\n" +
	"\x19UpdateProductStockRequest\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x14\n" +
	"\x05Stock\x18\x02 \x01(\x03R\x05Stock\"\xfa\x01\n" +
	"\x0fProductResponse\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bCategory\x18\x03 \x01(\tR\bCategory\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\x03R\x05Stock\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\x12\x18\n" +
	"\aMessage\x18\x06 \x01(\tR\aMessage\x12\x14\n" +
	"\x05Price\x18\a \x01(\x03R\x05Price\x12;\n" +
	"\fBaseResponse\x18\b \x01(\v2\x17.inventory.BaseResponseR\fBaseResponse\"8\n" +
	"\x18CheckProductStockRequest\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\"\x8c\x01\n" +
	"\x19CheckProductStockResponse\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x14\n" +
	"\x05Stock\x18\x02 \x01(\x03R\x05Stock\x12;\n" +
	"\fBaseResponse\x18\x03 \x01(\v2\x17.inventory.BaseResponseR\fBaseResponse\"}\n" +
	"\x15ReserveProductRequest\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x14\n" +
	"\x05Count\x18\x03 \x01(\x03R\x05Count\x12\x18\n" +
	"\aOrderID\x18\x04 \x01(\x03R\aOrderID\"\xd7\x01\n" +
	"\x16ReserveProductResponse\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12$\n" +
	"\rReserveStatus\x18\x03 \x01(\x03R\rReserveStatus\x12\"\n" +
	"\fReserveCount\x18\x04 \x01(\x03R\fReserveCount\x12;\n" +
	"\fBaseResponse\x18\x06 \x01(\v2\x17.inventory.BaseResponseR\fBaseResponse\"M\n" +
	"\x15ReleaseProductRequest\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"\x8d\x01\n" +
	"\x16ReleaseProductResponse\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12;\n" +
	"\fBaseResponse\x18\x03 \x01(\v2\x17.inventory.BaseResponseR\fBaseResponse\"\x9c\x01\n" +
	"\fBaseResponse\x12\x1c\n" +
	"\tRPCStatus\x18\x01 \x01(\x03R\tRPCStatus\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\"\n" +
	"\fErrorMessage\x18\x03 \x01(\tR\fErrorMessage\x120\n" +
	"\x13DisplayErrorMessage\x18\x04 \x01(\tR\x13DisplayErrorMessage2\xec\x04\n" +
	"\tInventory\x12X\n" +
	"\x12UpdateProductStock\x12$.inventory.UpdateProductStockRequest\x1a\x1a.inventory.ProductResponse\"\x00\x12N\n" +
	"\rUpdateProduct\x12\x1f.inventory.ProductMasterRequest\x1a\x1a.inventory.ProductResponse\"\x00\x12T\n" +
	"\x13UpdateProductStatus\x12\x1f.inventory.ProductMasterRequest\x1a\x1a.inventory.ProductResponse\"\x00\x12K\n" +
	"\n" +
	"AddProduct\x12\x1f.inventory.ProductMasterRequest\x1a\x1a.inventory.ProductResponse\"\x00\x12`\n" +
	"\x11CheckProductStock\x12#.inventory.CheckProductStockRequest\x1a$.inventory.CheckProductStockResponse\"\x00\x12W\n" +
	"\x0eReserveProduct\x12 .inventory.ReserveProductRequest\x1a!.inventory.ReserveProductResponse\"\x00\x12W\n" +
	"\x0eReleaseProduct\x12 .inventory.ReleaseProductRequest\x1a!.inventory.ReleaseProductResponse\"\x00B\x11Z\x0finventory.protob\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_inventory_proto_goTypes = []any{
	(*ProductMasterRequest)(nil),      // 0: inventory.ProductMasterRequest
	(*UpdateProductStockRequest)(nil), // 1: inventory.UpdateProductStockRequest
	(*ProductResponse)(nil),           // 2: inventory.ProductResponse
	(*CheckProductStockRequest)(nil),  // 3: inventory.CheckProductStockRequest
	(*CheckProductStockResponse)(nil), // 4: inventory.CheckProductStockResponse
	(*ReserveProductRequest)(nil),     // 5: inventory.ReserveProductRequest
	(*ReserveProductResponse)(nil),    // 6: inventory.ReserveProductResponse
	(*ReleaseProductRequest)(nil),     // 7: inventory.ReleaseProductRequest
	(*ReleaseProductResponse)(nil),    // 8: inventory.ReleaseProductResponse
	(*BaseResponse)(nil),              // 9: inventory.BaseResponse
}
var file_inventory_proto_depIdxs = []int32{
	9,  // 0: inventory.ProductResponse.BaseResponse:type_name -> inventory.BaseResponse
	9,  // 1: inventory.CheckProductStockResponse.BaseResponse:type_name -> inventory.BaseResponse
	9,  // 2: inventory.ReserveProductResponse.BaseResponse:type_name -> inventory.BaseResponse
	9,  // 3: inventory.ReleaseProductResponse.BaseResponse:type_name -> inventory.BaseResponse
	1,  // 4: inventory.Inventory.UpdateProductStock:input_type -> inventory.UpdateProductStockRequest
	0,  // 5: inventory.Inventory.UpdateProduct:input_type -> inventory.ProductMasterRequest
	0,  // 6: inventory.Inventory.UpdateProductStatus:input_type -> inventory.ProductMasterRequest
	0,  // 7: inventory.Inventory.AddProduct:input_type -> inventory.ProductMasterRequest
	3,  // 8: inventory.Inventory.CheckProductStock:input_type -> inventory.CheckProductStockRequest
	5,  // 9: inventory.Inventory.ReserveProduct:input_type -> inventory.ReserveProductRequest
	7,  // 10: inventory.Inventory.ReleaseProduct:input_type -> inventory.ReleaseProductRequest
	2,  // 11: inventory.Inventory.UpdateProductStock:output_type -> inventory.ProductResponse
	2,  // 12: inventory.Inventory.UpdateProduct:output_type -> inventory.ProductResponse
	2,  // 13: inventory.Inventory.UpdateProductStatus:output_type -> inventory.ProductResponse
	2,  // 14: inventory.Inventory.AddProduct:output_type -> inventory.ProductResponse
	4,  // 15: inventory.Inventory.CheckProductStock:output_type -> inventory.CheckProductStockResponse
	6,  // 16: inventory.Inventory.ReserveProduct:output_type -> inventory.ReserveProductResponse
	8,  // 17: inventory.Inventory.ReleaseProduct:output_type -> inventory.ReleaseProductResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
